### PR TITLE
Add Terms of Service page

### PR DESCRIPTION
**Pull request by EssaSaeed**
A taste:

image

image

### CODE REVIEW

**Comment by T-TonyLiang** [comment]
I modified the CSS for the button and resolved the conflicts. Here's what it looks like now.
image
Hovered:
image

**Comment by EssaSaeed** [comment]
> I modified the CSS for the button and resolved the conflicts. Here's what it looks like now.
> image
> Hovered:
> image

LGTM, do we want the "Available in the Chrome Web Store" to be on the same line as the button? (The left side is feeling a little bare because of it.) I don't mind leaving it like this thought :)

**Comment by T-TonyLiang** [comment]
I'm good with either too, we can move it or remove it

**Comment by EssaSaeed** [comment]
> I'm good with either too, we can move it or remove it

Ok, it's fine then, feel free to merge it :)

**Pull request merged**
